---
engines:
  scss-lint:
    enabled: true
  csslint:
    enabled: false
  eslint:
    enabled: true
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript

  # Misc
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - CHANGED
      - XXX
      - IDEA
      - HACK
      - NOTE
      - REVIEW
      - UPGRADEME
      - TESTME
      - CLEANME

ratings:
  paths:
  - "**.erb"
  - "**.rb"
  - "**.slim"
  - "**.css"
  - "**.sass"
  - "**.js"

exclude_paths:
- test/
- spec/
- db/
- vendor/
- node_modules/
