settings:
  import/resolver:
    babel-module: {}
    webpack:
      config: config/webpack/test.js

env:
  browser: true
  jquery: true
  es6: true

extends: airbnb-base

rules:
  semi: ['warn', 'never']
  comma-dangle: ['error', 'never']
