extends: airbnb-base

env:
  browser: true
  jquery: true
  es6: true

settings:
  import/resolver:
    webpack:
      config: 'config/webpack/shared.js'

rules:
  no-var: 1
  no-undef: 0
  indent: ['warn', 2]
  linebreak-style: ['warn', 'unix']
  quotes: ['warn', 'single']
  semi: ['warn', 'never']
  comma-dangle: ['error', never]
  import/extensions: 1
  import/no-extraneous-dependencies: 0
