extends: airbnb-base
plugins:
  - import

env:
  browser: true
  jquery: true
  es6: true

rules:
  no-var: 1
  no-undef: 0
  indent: ['warn', 2]
  linebreak-style: ['warn', 'unix']
  quotes: ['warn', 'single']
  semi: ['warn', 'never']
  comma-dangle: ['error', never]
  import/extensions: 0
