settings:
  import/resolver:
    webpack:
      config: 'config/webpack/shared.js'

env:
  browser: true
  jquery: true
  es6: true

extends: airbnb-base

rules:
  semi: ['warn', 'never']
  comma-dangle: ['error', never]
