require: rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/anthony-robin/rubocop-rules/master/.rubocop.yml
  - https://raw.githubusercontent.com/anthony-robin/rubocop-rules/master/.rubocop-rails.yml
  - https://raw.githubusercontent.com/anthony-robin/rubocop-rules/master/.rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1

RSpec/NamedSubject:
  Exclude:
    - spec/features/shared_examples/*.rb
