Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'

Bundler/OrderedGems:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
