Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: true # Disable all cops by default
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'

 # This cop identifies places where `gsub` can be replaced by `tr` or `delete`.
Performance/StringReplacement:
  Enabled: true

# Check for the correct use of Date methods, such as Date.today, Date.current etc
Rails/Date:
  Enabled: true

# Use 3.days instead of 3.day
Rails/PluralizationGrammar:
  Enabled: true

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true

# Do not use braces for hash literals when they are the last argument of a
# method call.
Style/BracesAroundHashParameters:
  Enabled: true

# Align `when` with `case`.
Style/CaseIndentation:
  Enabled: true

# Align comments with method definitions.
Style/CommentIndentation:
  Enabled: true

# No extra empty lines.
Style/EmptyLines:
  Enabled: true

# In a regular class definition, no empty lines around the body.
Style/EmptyLinesAroundClassBody:
  Enabled: true

# In a regular module definition, no empty lines around the body.
Style/EmptyLinesAroundModuleBody:
  Enabled: true

# Add empty lines below private, protected, ...
Style/EmptyLinesAroundAccessModifier:
  Enabled: true

# Do not write def my_method; end
Style/EmptyMethod:
  EnforcedStyle: expanded

# Detect double spaces
Style/ExtraSpacing:
  Enabled: true

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true

# Check whether comments have a leading space after the # denoting the start of the comment
Style/LeadingCommentSpace:
  Enabled: true

# Two spaces, no tabs (for indentation).
Style/IndentationWidth:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Style/SpaceAroundKeyword:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

# Defining a method with parameters needs parentheses.
Style/MethodDefParentheses:
  Enabled: true

# Do not use return for last method line
Style/RedundantReturn:
  Enabled: true

# Use `foo {}` not `foo{}`.
Style/SpaceBeforeBlockBraces:
  Enabled: true

# Use `foo { bar }` not `foo {bar}`.
Style/SpaceInsideBlockBraces:
  Enabled: true

# Use `{ a: 1 }` not `{a:1}`.
Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/SpaceInsideParens:
  Enabled: true

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# Check for array literals made up of symbols that are not using the %i() syntax
Style/SymbolArray:
  Enabled: true

# Check for array literals made up of word-like strings, that are not using the %w() syntax
Style/WordArray:
  Enabled: true

# Detect hard tabs, no hard tabs.
Style/Tab:
  Enabled: true

# Blank lines should not have any spaces.
Style/TrailingBlankLines:
  Enabled: true

# No trailing whitespace.
Style/TrailingWhitespace:
  Enabled: true

# Use quotes for string literals when they are enough.
Style/UnneededPercentQ:
  Enabled: true

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

# Use my_method(my_arg) not my_method( my_arg ) or my_method my_arg.
Lint/RequireParentheses:
  Enabled: true
