dist: trusty
sudo: required
language: ruby

rvm:
  - 2.4.2

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

services:
  - elasticsearch

env:
  - DB=sqlite

before_install:
  - export TZ=Europe/Paris

  # ChromeDriver
  - wget http://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION:-2.32}/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin/chromedriver
  - sudo chown root:root /usr/local/bin/chromedriver
  - sudo chmod 0755 /usr/local/bin/chromedriver

install:
  - bundle install --without development --path=${BUNDLE_PATH:-vendor/bundle} # Gems

  # Webpack (npm packages)
  - nvm install 7.7.0
  - npm i -g yarn
  - bin/yarn install

before_script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200 # ElasticSearch

  - cp .env{.sample,}
  - cp config/database.yml{.sample,}
  - RAILS_ENV=test bin/rails webpacker:compile
  - RAILS_ENV=test bin/rails db:migrate

script:
  - bin/rspec
  - bin/rubocop
  - bin/slim-lint app/views
  - bin/yarn run eslint
  - bin/yarn run sasslint

after_script:
  - RAILS_ENV=test bin/rails db:seed

after_failure:
  - date
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bin/rake --version
  - node --version
  - whereis google-chrome-stable
  - whereis chromedriver

matrix:
  fast_finish: true

branches:
  only:
    - master

addons:
  chrome: stable
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch

notifications:
  email: false
