DEFAULTS: &DEFAULTS
  admin: Anthony
  title: BlogMVC
  subtitle: En marche !
  phone: <%= ENV.fetch('PHONE_CONTACT') %>
  email: <%= ENV.fetch('TO_CONTACT') %>

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
