DEFAULTS: &DEFAULTS
  admin: Anthony
  title: BlogMVC
  subtitle: En marche !
  phone: <%= ENV.fetch('PHONE_CONTACT') %>
  email: <%= ENV.fetch('WEBMASTER_EMAIL') %>

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

staging:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
